Entity/LoginInfoInterface.php
<?php

namespace Oro\Bundle\UserBundle\Entity;

interface LoginInfoInterface
{
    /**
     * Gets the last login time.
     *
     * @return \DateTime
     */
    public function getLastLogin();

    /**
     * Gets login count number.
     *
     * @return int
     */
    public function getLoginCount();

    /**
     * @param \DateTime $time New login time
     *
     * @return $this
     */
    public function setLastLogin(\DateTime $time);

    /**
     * @param int $count New login count value
     *
     * @return $this
     */
    public function setLoginCount($count);
}

Controller/Api/Rest/UserController.php
<?php

namespace Oro\Bundle\UserBundle\Controller\Api\Rest;

use Symfony\Component\Form\FormInterface;

use Nelmio\ApiDocBundle\Annotation\ApiDoc;

use FOS\RestBundle\Util\Codes;
use FOS\RestBundle\Routing\ClassResourceInterface;
use FOS\RestBundle\Controller\Annotations\NamePrefix;
use FOS\RestBundle\Controller\Annotations\QueryParam;

use Oro\Bundle\SecurityBundle\Annotation\Acl;
use Oro\Bundle\SecurityBundle\Annotation\AclAncestor;

use Oro\Bundle\SoapBundle\Controller\Api\Rest\RestController;
use Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager;
use Oro\Bundle\SoapBundle\Form\Handler\ApiFormHandler;

use Oro\Bundle\UserBundle\Entity\User;
use Oro\Bundle\UserBundle\Entity\Role;
use Oro\Bundle\UserBundle\Entity\Group;
use Oro\Bundle\UserBundle\Entity\Email;

use Oro\Bundle\OrganizationBundle\Entity\BusinessUnit;

/**
 * @NamePrefix("oro_api_")
 */
class UserController extends RestController implements ClassResourceInterface
{
    /**
     * Get the list of users
     *
     * @QueryParam(
     *      name="page",
     *      requirements="\d+",
     *      nullable=true,
     *      description="Page number, starting from 1. Defaults to 1."
     * )
     * @QueryParam(
     *      name="limit",
     *      requirements="\d+",
     *      nullable=true,
     *      description="Number of items per page. defaults to 10."
     * )
     * @QueryParam(
     *     name="phone",
     *     requirements=".+",
     *     nullable=true,
     *     description="Phone number."
     * )
     *
     * @return \Symfony\Component\HttpFoundation\Response
     * @ApiDoc(
     *      description="Get the list of users",
     *      resource=true,
     *      filters={
     *          {"name"="page", "dataType"="integer"},
     *          {"name"="limit", "dataType"="integer"}
     *      }
     * )
     * @AclAncestor("oro_user_user_view")
     */
    public function cgetAction()
    {
        $page  = (int) $this->getRequest()->get('page', 1);
        $limit = (int) $this->getRequest()->get('limit', self::ITEMS_PER_PAGE);

        $criteria = $this->getFilterCriteria($this->getSupportedQueryParameters(__FUNCTION__));

        return $this->handleGetListRequest($page, $limit, $criteria);
    }

    /**
     * Get user data
     *
     * @param int $id User id
     *
     * @return \Symfony\Component\HttpFoundation\Response
     * @ApiDoc(
     *      description="Get user data",
     *      resource=true,
     *      requirements={
     *          {"name"="id", "dataType"="integer"},
     *      }
     * )
     * @AclAncestor("oro_user_user_view")
     */
    public function getAction($id)
    {
        return $this->handleGetRequest($id);
    }

    /**
     * Create new user
     *
     * @return \Symfony\Component\HttpFoundation\Response
     * @ApiDoc(
     *      description="Create new user",
     *      resource=true
     * )
     * @AclAncestor("oro_user_user_create")
     */
    public function postAction()
    {
        return $this->handleCreateRequest();
    }

    /**
     * Update existing user
     *
     * @param int $id User id
     *
     * @return \Symfony\Component\HttpFoundation\Response
     * @ApiDoc(
     *      description="Update existing user",
     *      resource=true,
     *      requirements={
     *          {"name"="id", "dataType"="integer"},
     *      }
     * )
     * @AclAncestor("oro_user_user_update")
     */
    public function putAction($id)
    {
        return $this->handleUpdateRequest($id);
    }

    /**
     * Delete user
     *
     * @param int $id User id
     *
     * @return \Symfony\Component\HttpFoundation\Response
     * @ApiDoc(
     *      description="Delete user",
     *      resource=true,
     *      requirements={
     *          {"name"="id", "dataType"="integer"},
     *      }
     * )
     * @Acl(
     *      id="oro_user_user_delete",
     *      type="entity",
     *      class="OroUserBundle:User",
     *      permission="DELETE"
     * )
     */
    public function deleteAction($id)
    {
        return $this->handleDeleteRequest($id);
    }

    /**
     * Get user roles
     *
     * @param int $id User id
     *
     * @return \Symfony\Component\HttpFoundation\Response
     * @ApiDoc(
     *      description="Get user roles",
     *      resource=true,
     *      requirements={
     *          {"name"="id", "dataType"="integer"},
     *      }
     * )
     * @AclAncestor("oro_user_role_view")
     */
    public function getRolesAction($id)
    {
        $entity = $this->getManager()->find($id);

        if (!$entity) {
            return $this->handleView($this->view('', Codes::HTTP_NOT_FOUND));
        }

        return $this->handleView($this->view($entity->getRoles(), Codes::HTTP_OK));
    }

    /**
     * Get user groups
     *
     * @param int $id User id
     *
     * @return \Symfony\Component\HttpFoundation\Response
     * @ApiDoc(
     *      description="Get user groups",
     *      resource=true,
     *      requirements={
     *          {"name"="id", "dataType"="integer"},
     *      }
     * )
     * @AclAncestor("oro_user_group_view")
     */
    public function getGroupsAction($id)
    {
        $entity = $this->getManager()->find($id);

        if (!$entity) {
            return $this->handleView($this->view('', Codes::HTTP_NOT_FOUND));
        }

        return $this->handleView($this->view($entity->getGroups(), Codes::HTTP_OK));
    }

    /**
     * Filter user by username or email
     *
     * @QueryParam(
     *      name="email",
     *      requirements="[a-zA-Z0-9\-_\.@]+",
     *      nullable=true,
     *      description="Email to filter"
     * )
     * @QueryParam(
     *      name="username",
     *      requirements="[a-zA-Z0-9\-_\.]+",
     *      nullable=true,
     *      description="Username to filter"
     * )
     *
     * @return \Symfony\Component\HttpFoundation\Response
     *
     * @ApiDoc(
     *      description="Get user by username or email",
     *      resource=true,
     *      filters={
     *          {"name"="email", "dataType"="string"},
     *          {"name"="username", "dataType"="string"}
     *      }
     * )
     * @AclAncestor("oro_user_user_view")
     */
    public function getFilterAction()
    {
        $params = array_intersect_key(
            $this->getRequest()->query->all(),
            array_flip($this->getSupportedQueryParameters(__FUNCTION__))
        );

        if (empty($params)) {
            return $this->handleView($this->view('', Codes::HTTP_NOT_FOUND));
        }

        /** @var User $entity */
        $entity = $this->getManager()->getRepository()->findOneBy($params);
        if (!$entity) {
            return $this->handleView($this->view('', Codes::HTTP_NOT_FOUND));
        }

        $result = $this->getPreparedItem($entity);

        return $this->buildResponse($result, self::ACTION_READ, ['result' => $result], Codes::HTTP_OK);
    }

    /**
     * {@inheritdoc}
     */
    protected function transformEntityField($field, &$value)
    {
        switch ($field) {
            case 'roles':
                $result = [];
                /** @var Role $role */
                foreach ($value as $index => $role) {
                    $result[$index] = [
                        'id'    => $role->getId(),
                        'role'  => $role->getRole(),
                        'label' => $role->getLabel(),
                    ];
                }
                $value = $result;
                break;
            case 'groups':
                $result = [];
                /** @var Group $group */
                foreach ($value as $index => $group) {
                    $result[$index] = [
                        'id'   => $group->getId(),
                        'name' => $group->getName()
                    ];
                }
                $value = $result;
                break;
            case 'emails':
                $result = [];
                /** @var Email $email */
                foreach ($value as $email) {
                    $result[] = $email->getEmail();
                }
                $value = $result;
                break;
            case 'businessUnits':
                $result = [];
                /** @var BusinessUnit $businessUnit */
                foreach ($value as $index => $businessUnit) {
                    $result[$index] = [
                        'id'   => $businessUnit->getId(),
                        'name' => $businessUnit->getName()
                    ];
                }
                $value = $result;
                break;
            case 'organization':
                if ($value) {
                    $value = $value->getName();
                }
                break;
            case 'owner':
                if ($value) {
                    $value = [
                        'id'   => $value->getId(),
                        'name' => $value->getName()
                    ];
                }
                break;
            default:
                parent::transformEntityField($field, $value);
        }
    }

    /**
     * {@inheritdoc}
     */
    protected function getPreparedItem($entity, $resultFields = [])
    {
        $result = parent::getPreparedItem($entity);

        unset($result['salt']);
        unset($result['password']);
        unset($result['confirmationToken']);
        unset($result['passwordRequestedAt']);
        unset($result['imapConfiguration']);
        unset($result['currentStatus']);
        unset($result['statuses']);
        unset($result['apiKeys']);
        unset($result['organizations']);
        unset($result['emailOrigins']);

        //todo: Add user avatar to api
        /*$result['imagePath'] = null;
        if (isset($result['image'])) {
            $result['imagePath'] = $this->getRequest()->getBasePath() . '/' . $entity->getImagePath();
        }
        unset($result['image']);*/

        return $result;
    }

    /**
     * Get entity Manager

Controller/Api/Soap/UserController.php
<?php

namespace Oro\Bundle\UserBundle\Controller\Api\Soap;

use BeSimple\SoapBundle\ServiceDefinition\Annotation as Soap;

use Oro\Bundle\SecurityBundle\Annotation\AclAncestor;
use Oro\Bundle\SoapBundle\Controller\Api\Soap\SoapController;

use Oro\Bundle\UserBundle\Entity\UserSoap;
use Oro\Bundle\UserBundle\Entity\User;

class UserController extends SoapController
{
    /**
     * @Soap\Method("getUsers")
     * @Soap\Param("page", phpType="int")
     * @Soap\Param("limit", phpType="int")
     * @Soap\Result(phpType="Oro\Bundle\UserBundle\Entity\UserSoap[]")
     * @AclAncestor("oro_user_user_view")
     */
    public function cgetAction($page = 1, $limit = 10)
    {
        return $this->handleGetListRequest($page, $limit);
    }

    /**
     * @Soap\Method("getUser")
     * @Soap\Param("id", phpType="int")
     * @Soap\Result(phpType="Oro\Bundle\UserBundle\Entity\UserSoap")
     * @AclAncestor("oro_user_user_view")
     */
    public function getAction($id)
    {
        return $this->handleGetRequest($id);
    }

    /**
     * @Soap\Method("createUser")
     * @Soap\Param("user", phpType="Oro\Bundle\UserBundle\Entity\UserSoap")
     * @Soap\Result(phpType="int")
     * @AclAncestor("oro_user_user_create")
     */
    public function createAction($user)
    {
        return $this->handleCreateRequest();
    }

    /**
     * @Soap\Method("updateUser")
     * @Soap\Param("id", phpType="int")
     * @Soap\Param("user", phpType="Oro\Bundle\UserBundle\Entity\UserSoap")
     * @Soap\Result(phpType="boolean")
     * @AclAncestor("oro_user_user_update")
     */
    public function updateAction($id, $user)
    {
        return $this->handleUpdateRequest($id);
    }

    /**
     * @Soap\Method("deleteUser")
     * @Soap\Param("id", phpType="int")
     * @Soap\Result(phpType="boolean")
     * @AclAncestor("oro_user_user_delete")
     */
    public function deleteAction($id)
    {
        return $this->handleDeleteRequest($id);
    }

    /**
     * @Soap\Method("getUserRoles")
     * @Soap\Param("id", phpType="int")
     * @Soap\Result(phpType="Oro\Bundle\UserBundle\Entity\RoleSoap[]")
     * @AclAncestor("oro_user_role_view")
     */
    public function getRolesAction($id)
    {
        return $this->transformToSoapEntities($this->getEntity($id)->getRoles());
    }

    /**
     * @Soap\Method("getUserGroups")
     * @Soap\Param("id", phpType="int")
     * @Soap\Result(phpType="Oro\Bundle\UserBundle\Entity\GroupSoap[]")
     * @AclAncestor("oro_user_group_view")
     */
    public function getGroupsAction($id)
    {
        return $this->transformToSoapEntities($this->getEntity($id)->getGroups());
    }

    /**
     * @Soap\Method("getUserBy")
     * @Soap\Param("filters", phpType="Oro\Bundle\SoapBundle\Type\KeyValue\StringType[]")
     * @Soap\Result(phpType="Oro\Bundle\UserBundle\Entity\UserSoap")
     * @AclAncestor("oro_user_user_view")
     */
    public function getByAction(array $filters)
    {
        if (empty($filters)) {
            throw new \SoapFault('NOT_FOUND', 'Empty filter data');
        }

        $entity = $this->getUserManager()->findUserBy($filters);

        if (!$entity) {
            throw new \SoapFault('NOT_FOUND', 'User cannot be found using specified filter');
        }

        return $this->transformToSoapEntity($entity);
    }

    /**
     * {@inheritdoc}
     */
    protected function fixFormData(array &$data, $entity)
    {
        parent::fixFormData($data, $entity);

        unset($data['id']);
        unset($data['lastLogin']);

        if ($entity instanceof User &&
            $entity->getId() &&
            !$this->container->get('oro_security.security_facade')->isGranted('ASSIGN', $entity)
        ) {
            unset($data['owner']);
        }

        return true;
    }

    /**
     * @return \Oro\Bundle\UserBundle\Entity\UserManager
     */
    protected function getUserManager()
    {
        return $this->container->get('oro_user.manager');
    }

    /**
     * @return \Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
     */
    public function getManager()
    {
        return $this->container->get('oro_user.manager.api');
    }

    /**
     * @inheritdoc
     */
    public function getForm()
    {
        return $this->container->get('oro_user.form.user.api');
    }

    /**
     * @inheritdoc
     */
    public function getFormHandler()
    {
        return $this->container->get('oro_user.form.handler.user.api');
    }

    /**
     * {@inheritdoc}
     */
    protected function getDeleteHandler()
    {
        return $this->container->get('oro_user.handler.delete');
    }
}

Resources/views/User/forcePasswordResetButton.html.twig
{{ UI.clientButton({
    'dataUrl': path('oro_user_send_forced_password_reset_email', {id: entity.id}),
    'aCss': 'no-hash',
    'iCss': 'icon-unlock-alt',
    'dataId': entity.id,
    'label': 'oro.user.password.reset_password.label'|trans,
    'widget': {
        'type': 'dialog',
        'multiple': false,
        'options': {
            'alias': 'force-password-reset-dialog',
            'dialogOptions' : {
                'title' : 'oro.user.password.reset_dialog.title'|trans,
                'allowMaximize': false,
                'allowMinimize': false,
                'autoResize': true
            }
        }
    }
}) }}

Resources/views/User/forcePasswordResetLink.html.twig
{{ UI.clientLink({
    'dataUrl': path('oro_user_send_forced_password_reset_email', {id: entity.id}),
    'aCss': 'no-hash',
    'iCss': 'icon-unlock-alt',
    'dataId': entity.id,
    'label': 'oro.user.password.reset_password.label'|trans,
    'widget': {
        'type': 'dialog',
        'multiple': false,
        'options': {
            'alias': 'force-password-reset-dialog',
            'dialogOptions' : {
                'title' : 'oro.user.password.reset_dialog.title'|trans,
                'allowMaximize': false,
                'allowMinimize': false,
                'autoResize': true
            }
        }
    }
}) }}

Resources/views/User/index.html.twig
{% extends 'OroUIBundle:actions:index.html.twig' %}
{% import 'OroUIBundle::macros.html.twig' as UI %}
{% set gridName = 'users-grid' %}
{% set pageTitle = 'oro.user.entity_plural_label'|trans %}

{% block navButtons %}
    {% include 'OroImportExportBundle:ImportExport:buttons.html.twig' with {
        exportProcessor: 'oro_user',
        exportTemplateProcessor: 'oro_user'
    } %}

    {% if resource_granted('oro_user_user_create') %}
        <div class="btn-group">
            {{ UI.addButton({
            'path': path('oro_user_create'),
            'entity_label': 'oro.user.entity_label'|trans
            }) }}
        </div>
    {% endif %}
{% endblock %}

Resources/views/User/update.html.twig
{% extends 'OroUIBundle:actions:update.html.twig' %}
{% form_theme form with ['OroFormBundle:Form:fields.html.twig'] %}

{% set fullname = form.vars.value|oro_format_name|default('N/A') %}
{% oro_title_set({params : {"%username%": fullname }}) %}

{% set formAction = form.vars.value.id ? path('oro_user_update', { id: form.vars.value.id}) : path('oro_user_create') %}

{% block navButtons %}
    {% if form.vars.value.id and resource_granted('DELETE', form.vars.value) and form.vars.value.id != app.user.id %}
        {{ UI.deleteButton({
            'dataUrl': path('oro_api_delete_user', {'id': form.vars.value.id}),
            'dataRedirect': path('oro_user_index'),
            'aCss': 'no-hash remove-button',
            'id': 'btn-remove-user',
            'dataId':  form.vars.value.id,
            'entity_label': 'oro.user.entity_label'|trans,
            'disabled': not allow_delete
        }) }}
        {{ UI.buttonSeparator() }}
    {% endif %}
    {{ UI.cancelButton(path('oro_user_index')) }}
    {% set html = UI.saveAndCloseButton({
        'route': 'oro_user_view',
        'params': {'id': '$id'}
    }) %}
    {% if resource_granted('oro_user_create') %}
        {% set html = html ~ UI.saveAndNewButton({
            'route': 'oro_user_create'
        }) %}
    {% endif %}
    {% if form.vars.value.id or resource_granted('oro_user_user_update') %}
        {% set html = html ~ UI.saveAndStayButton({
            'route': 'oro_user_update',
            'params': {'id': '$id'}
        }) %}
    {% endif %}
    {{ UI.dropdownSaveButton({'html': html}) }}
    {{ parent() }}
{% endblock navButtons %}

{% block pageHeader %}
    {% if form.vars.value.id %}
        {% set breadcrumbs = {
            'entity':      form.vars.value,
            'indexPath':   path('oro_user_index'),
            'indexLabel': 'oro.user.entity_plural_label'|trans,
            'entityTitle': fullname,
        }
        %}
        {% set avatar = oro_configured_image_url(form.vars.value, 'avatar') %}
        {{ parent() }}
    {% else %}
        {% set title = 'oro.ui.create_entity'|trans({'%entityName%': 'oro.user.entity_label'|trans}) %}
        {% include 'OroUIBundle::page_title_block.html.twig' with { title: title } %}
    {% endif %}
{% endblock pageHeader %}

{% block stats %}
    <li>{{ 'oro.ui.created_at'|trans }}: {{ form.vars.value.createdAt ? form.vars.value.createdAt|oro_format_datetime : 'N/A' }}</li>
    <li>{{ 'oro.ui.updated_at'|trans }}: {{ form.vars.value.updatedAt ? form.vars.value.updatedAt|oro_format_datetime : 'N/A' }}</li>
    <li>{{ 'oro.user.last_login.label'|trans }}: {{ form.vars.value.lastLogin ? form.vars.value.lastLogin|oro_format_datetime : 'N/A' }}</li>
    <li>{{ 'oro.user.login_count.label'|trans }}: {{ form.vars.value.loginCount|default(0) }}</li>
{% endblock stats %}

{% block content_data %}
<div class="user-profile-cols">
    {% set id = 'user-profile' %}

    {% set dataBlocks = [{
        'title': 'General'|trans,
        'class': 'active',
        'subblocks': [
            {
                'title': '',
                'data': [
                    form.enabled is defined ? form_row(form.enabled),
                    form_row(form.username),
                    form.plainPassword is defined ? form_row(form.plainPassword) : '',
                    form_row(form.namePrefix),
                    form_row(form.firstName),
                    form_row(form.middleName),
                    form_row(form.lastName),
                    form_row(form.nameSuffix),
                    form_row(form.birthday),
                    form_row(form.avatar),
                    form.vars.value.id ? '' : form_row(form.inviteUser),
                ]
            },
            {
                'title': '',
                'data': [
                    form_row(form.email),
                    UI.collectionField(form.emails, 'oro.user.emails.label'|trans, 'Add another email'|trans),
                    form_row(form.phone),
                ]
            }
        ]
    }] %}

    {% set additionalData = [] %}
    {% for child in form.children if child.vars.extra_field is defined and child.vars.extra_field %}
        {% set additionalData = additionalData|merge([form_row(child)]) %}
    {% endfor %}
    {% if additionalData is not empty %}
        {% set dataBlocks = dataBlocks|merge([{
            'title': 'Additional'|trans,
            'subblocks': [{
                'title': '',
                'useSpan': false,
                'data' : additionalData
            }]
        }] ) %}
    {% endif %}

    {% set hasGroups = form.groups is defined %}
    {% set hasRoles = form.roles is defined %}
    {% if hasGroups or hasRoles %}
        {% set userGroups %}
            {% if hasGroups %}
                {{ form_row(form.groups, {attr: { class: 'horizontal' } }) }}
            {% endif %}
        {% endset %}

        {% set userRoles %}
            {% if hasRoles %}
                <div class="form-horizontal" id="roles-list">
                    {{ form_row(form.roles, {attr: { class: 'horizontal' } }) }}
                </div>
            {% endif %}
        {% endset %}

        {% set title = '' %}
        {% if hasGroups and hasRoles %}
            {% set title = '%groups% and %roles%'|trans({
                '%groups%' : 'oro.user.groups.label'|trans,
                '%roles%' : 'oro.user.roles.label'|trans
            }) %}
        {% elseif hasGroups %}
            {% set title = 'oro.user.groups.label'|trans %}
        {% elseif hasRoles %}
            {% set title = 'oro.user.roles.label'|trans %}
        {% endif %}

        {% set dataBlocks = dataBlocks|merge( [{
            'title': title,
            'subblocks': [
                {
                    'title': '',
                    'data': [userGroups, userRoles]
                }
            ]
        }] ) %}
    {% endif %}

    {% if form.organizations is defined %}
        {% set dataBlocks = dataBlocks|merge( [{
            'title': 'Access Settings'|trans,
            'subblocks': [{
                'title': '',
                'useSpan': false,
                'data': [form_row(form.organizations)]
            }]
        }] ) %}
    {% endif %}

    {% if form.change_password is defined %}
        {% set dataBlocks = dataBlocks|merge( [{
            'title': 'oro.user.password.label'|trans,
            'subblocks': [
                {
                    'title': '',
                    'data': [
                        form_widget(form.change_password)
                    ]
                }
            ]
        }] ) %}
    {% endif %}

    {% set data = {
        'formErrors': form_errors(form)? form_errors(form) : null,
        'dataBlocks': dataBlocks,
    } %}
    {{ parent() }}
    </div>
{% endblock content_data %}

Resources/views/User/view.html.twig
{% extends 'OroUIBundle:actions:view.html.twig' %}
{% import 'OroUIBundle::macros.html.twig' as UI %}

{% set fullname = entity|oro_format_name|default('N/A') %}
{% oro_title_set({params : {"%username%": fullname }}) %}

{% block navButtons %}
    {% placeholder view_navButtons with {entity: entity} %}
    {% if isDesktopVersion() %}
        {% if resource_granted('CONFIGURE', entity) and not isProfileView %}
            {{ UI.button({
                'path' : path('oro_user_config', { 'id': entity.id }),
                'label': 'oro.user.user_configuration.label'|trans,
                'title': 'oro.user.user_configuration.label'|trans,
                'iCss': 'icon-cog',
            }) }}
        {% elseif isProfileView and resource_granted('update_own_configuration') %}
            {{ UI.button({
                'path' : path('oro_user_profile_configuration'),
                'label': 'oro.user.user_configuration.label'|trans,
                'title': 'oro.user.user_configuration.label'|trans,
                'iCss': 'icon-cog',
            }) }}
        {% endif %}
    {% endif %}
    {% if resource_granted('EDIT', entity) %}
            {{ UI.editButton({
                'path' : path('oro_user_update', { id: entity.id }),
                'entity_label': 'oro.user.entity_label'|trans
            }) }}
    {% else %}
        {% if isProfileView and resource_granted('update_own_profile') %}
            {{ UI.editButton({
                'path': path('oro_user_profile_update'),
                'entity_label': 'profile'|trans
            }) }}
        {% endif %}
    {% endif %}
    {% if resource_granted('DELETE', entity) and entity.id != app.user.id %}
        {{ UI.deleteButton({
            'dataUrl': path('oro_api_delete_user', {'id': entity.id}),
            'dataRedirect': path('oro_user_index'),
            'aCss': 'no-hash remove-button',
            'id': 'btn-remove-user',
            'dataId': entity.id,
            'entity_label': 'oro.user.entity_label'|trans,
            'disabled': not allow_delete
        }) }}
    {% endif %}
{% endblock navButtons %}

{% block pageHeader %}
    {% set breadcrumbs = {
        'entity':      entity,
        'indexPath':   path('oro_user_index'),
        'indexLabel':  'oro.user.entity_plural_label'|trans,
        'entityTitle': fullname,
    } %}
    {% set avatar = oro_configured_image_url(entity, 'avatar') %}
    {{ parent() }}
{% endblock pageHeader %}

{% block breadcrumbs %}
    {{ parent() }}
    <div class="pull-left">
        {% if entity.enabled %}
            <div class="badge badge-enabled status-enabled"><i class="icon-status-enabled icon-circle"></i>
                {{- 'oro.user.enabled.enabled'|trans -}}
            </div>
        {% else %}
            <div class="badge badge-disabled status-disabled"><i class="icon-status-disabled icon-circle"></i>
                {{- 'oro.user.enabled.disabled'|trans -}}
            </div>
        {% endif %}
    </div>
    <div class="pull-left">
        {% if entity.authStatus.id == 'expired' %}
            <div class="badge badge-disabled status-disabled"><i class="icon-status-disabled icon-unlock-alt"></i>
                {{- entity.authStatus.name -}}</div>
        {% elseif entity.authStatus.id == 'active' %}
            <div class="badge badge-enabled status-enabled"><i class="icon-status-enabled icon-unlock"></i>
                {{- entity.authStatus.name -}}</div>
        {% else %}
            <div class="badge badge-tentatively status-tentatively"><i class="icon-status-tentatively icon-lock"></i>
                {{- entity.authStatus.name -}}</div>
        {% endif %}
    </div>
{% endblock breadcrumbs %}

{% block stats %}
    <li>{{ 'oro.ui.created_at'|trans }}: {{ entity.createdAt ? entity.createdAt|oro_format_datetime : 'N/A' }}</li>
    <li>{{ 'oro.ui.updated_at'|trans }}: {{ entity.updatedAt ? entity.updatedAt|oro_format_datetime : 'N/A' }}</li>
    <li>{{ 'oro.user.last_login.label'|trans }}: {{ entity.lastLogin ? entity.lastLogin|oro_format_datetime : 'N/A' }}</li>
    <li>{{ 'oro.user.login_count.label'|trans }}: {{ entity.loginCount|default(0) }}</li>
{% endblock stats %}

{% block content_data %}
    {% set userInformationWidget %}
        {{ oro_widget_render({
            'widgetType': 'block',
            'url': path('oro_user_widget_info', {id: entity.id, viewProfile: isProfileView })
        }) }}
    {% endset %}
    {% set dataBlocks = [
        {
            'title': 'General Information'|trans,
            'class': 'active',
            'subblocks': [
                {'data' : [userInformationWidget]}
            ]
        }
    ] %}

    {% set id = 'userView' %}
    {% set data = { 'dataBlocks': dataBlocks } %}
    {{ parent() }}
{% endblock content_data %}